#!/usr/bin/env bash

echo "Beep-Boop! I will ease your life by making your decisions for you! Just
enter in your choices one by one, then enter the word 'done' once you are ready
for me to make a choice!"

echo ""

declare -a choices
finished=false
while ! "$finished" && read -p "Entry: " ; do
  case "$REPLY" in
    "done") finished=true ;;
    *)    choices+=("$REPLY")
  esac
done

sleep .5
echo ""
sleep .5
echo "Number of choices: ${#choices[@]}"
sleep .5
echo "Brrp..Brrp.. Making choice at random!"
sleep .5
echo ""
sleep 2

let idx=( $RANDOM % ${#choices[@]} )

echo "Choice: ${choices[$idx]}"
sleep 1
